SELECT 
    CH.CAR_ID,
    ROUND(AVG(TIMESTAMPDIFF(DAY, CH.START_DATE, CH.END_DATE)+1), 1) AS AVG_DAYS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
GROUP BY CH.CAR_ID
HAVING AVG(TIMESTAMPDIFF(DAY, CH.START_DATE, CH.END_DATE)+1) >= 7
ORDER BY 
    AVG_DAYS DESC,      
    CH.CAR_ID DESC;      
