-- 코드를 입력하세요
with ANIMAL_STIL_IN as (
    SELECT AI.NAME, AI.DATETIME
    from ANIMAL_INS AI left join ANIMAL_OUTS AO
    on AI.ANIMAL_ID = AO.ANIMAL_ID
    where AO.DATETIME IS NULL
    order by AI.DATETIME ASC
) 

SELECT *
from ANIMAL_STIL_IN
where ROWNUM <=3