-- 코드를 입력하세요
with HISTORY_ID_RENTAL_FEE as(
    select CRCRH.HISTORY_ID, CRCC.CAR_ID, CRCC.CAR_TYPE ,(TIMESTAMPDIFF(DAY, CRCRH.START_DATE, CRCRH.END_DATE)+1)*CRCC.DAILY_FEE as 'TOTAL_FEE', case 
    when TIMESTAMPDIFF(DAY, CRCRH.START_DATE, CRCRH.END_DATE)+1 >= 90 then '90일 이상'
    when TIMESTAMPDIFF(DAY, CRCRH.START_DATE, CRCRH.END_DATE)+1 >= 30 then '30일 이상'
    when TIMESTAMPDIFF(DAY, CRCRH.START_DATE, CRCRH.END_DATE)+1 >= 7 then '7일 이상'
    else '기본'
    end as 'DURATION_TYPE'
    from CAR_RENTAL_COMPANY_RENTAL_HISTORY as CRCRH left join CAR_RENTAL_COMPANY_CAR as CRCC
    on CRCRH.CAR_ID = CRCC.CAR_ID
    where CRCC.CAR_TYPE = '트럭'
)
select HIRF.HISTORY_ID, case
when HIRF.DURATION_TYPE = '기본' then HIRF.TOTAL_FEE
when HIRF.DURATION_TYPE = '7일 이상' then round(HIRF.TOTAL_FEE * (100-CRCDP.DISCOUNT_RATE) / 100, 0)
when HIRF.DURATION_TYPE = '30일 이상' then round(HIRF.TOTAL_FEE * (100-CRCDP.DISCOUNT_RATE) / 100, 0)
when HIRF.DURATION_TYPE = '90일 이상' then round(HIRF.TOTAL_FEE * (100-CRCDP.DISCOUNT_RATE) / 100, 0)
end as FEE
from HISTORY_ID_RENTAL_FEE as HIRF left join CAR_RENTAL_COMPANY_DISCOUNT_PLAN as CRCDP
on HIRF.DURATION_TYPE = CRCDP.DURATION_TYPE and HIRF.CAR_TYPE = CRCDP.car_type
order by FEE DESC, HISTORY_ID DESC